name: myTest

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run a specific test with Maven
        run: mvn -Dtest=org.jsoup.parser.myCharacterReaderTest#testMethod test

      - name: Run tests with Maven
        run: mvn test | tee test-output.log

      - name: Display test results
        run: |
          echo "Les résultats des tests :"
          grep 'Running org.jsoup.parser.myCharacterReaderTest' test-output.log
          grep 'Tests run:' test-output.log
          
